// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syxvtsymncobshazvxzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5eHZ0c3ltbmNvYnNoYXp2eHpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODA2NDYsImV4cCI6MjA3MTI1NjY0Nn0.EPNK8uz2hausDiZ4gZA4-hyx42rukZ4dmHbdOl44ijY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});